// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkmFV7NO3D-CEJIQaZ0CcNkgmNOhnNh4',
    appId: '1:150976939377:web:ebf4f35956e35a681262d0',
    messagingSenderId: '150976939377',
    projectId: 'adds-37896',
    authDomain: 'adds-37896.firebaseapp.com',
    storageBucket: 'adds-37896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVnFFcIu3yzMRlpE1dGK1c4l7t4NSXMl8',
    appId: '1:150976939377:android:83613356bf4a64441262d0',
    messagingSenderId: '150976939377',
    projectId: 'adds-37896',
    storageBucket: 'adds-37896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOxX2-zopbf0dcdZ_XYq93BwH96Kxm5E',
    appId: '1:150976939377:ios:16ae21baac3cc5751262d0',
    messagingSenderId: '150976939377',
    projectId: 'adds-37896',
    storageBucket: 'adds-37896.appspot.com',
    iosClientId: '150976939377-h1au1mb2vgifajdoph10osvrr9sqbv7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.adds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdOxX2-zopbf0dcdZ_XYq93BwH96Kxm5E',
    appId: '1:150976939377:ios:16ae21baac3cc5751262d0',
    messagingSenderId: '150976939377',
    projectId: 'adds-37896',
    storageBucket: 'adds-37896.appspot.com',
    iosClientId: '150976939377-h1au1mb2vgifajdoph10osvrr9sqbv7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.adds',
  );
}
